### ISSUE TITLE
Bug report | Windows Redis Issue

### ISSUE THREAD

**Issue by EMREOYUN** [KockaAdmiralac/KockaLogger#39]
## Description
Redis can not be startable and npm start command fails because of Redis not found.

## Reproduction steps
Steps to reproduce the behavior(Windows only):
1. Install packages.
2. Start the program with corrent config.

## Expected behavior
Redis should up and no errors happen about Redis

## Media
![image](https://user-images.githubusercontent.com/35144629/102761572-22990900-4388-11eb-88a0-2353d371b60d.png)

## Notes
Windows Server 2012 R2 with Redis(Windows Version) Installed.

**Comment by KockaAdmiralac** [comment]
As of v1.1, KockaLogger expects Redis to be running, so the Redis server needs to be started up with `redis-server redis.conf` (on Linux, `./redis.sh start`). Does that work for you?

Also, since you're trying to start up KockaLogger, I need to cite this part of the README:
> After Fandom decided to forbid WikiaActivityLogger on 25th June 2018, they provided an alternative solution to wiki activity logging that does not consume as much server (and bot) resources. This solution, however, is not publicly available and therefore KockaLogger cannot be used by any Fandom user like WikiaActivityLogger could.

Have you obtained the necessary configuration? If you haven't, you might be interested in a solution such as [RcGcDw](https://gitlab.com/piotrex43/RcGcDw) instead.

**Comment by EMREOYUN** [comment]
> As of v1.1, KockaLogger expects Redis to be running, so the Redis server needs to be started up with `redis-server redis.conf` (on Linux, `./redis.sh start`). Does that work for you?
> 
> Also, since you're trying to start up KockaLogger, I need to cite this part of the README:
> 
> > After Fandom decided to forbid WikiaActivityLogger on 25th June 2018, they provided an alternative solution to wiki activity logging that does not consume as much server (and bot) resources. This solution, however, is not publicly available and therefore KockaLogger cannot be used by any Fandom user like WikiaActivityLogger could.
> 
> Have you obtained the necessary configuration? If you haven't, you might be interested in a solution such as [RcGcDw](https://gitlab.com/piotrex43/RcGcDw) instead.

.sh files cannot be run because i'm using Windows Server

**Comment by KockaAdmiralac** [comment]
Yeah, as I said, you can run `redis-server redis.conf` from the project directory to start up the Redis server on Windows (or use something like Cygwin, WSL or Git Bash to run them).

**Comment by EMREOYUN** [comment]
> Yeah, as I said, you can run `redis-server redis.conf` from the project directory to start up the Redis server on Windows (or use something like Cygwin, WSL or Git Bash to run them).

It can't. Redis installed for another project and since config made for Linux, Windows Version Redis can't run unless i need remove half of config(it does not work with this way also).

**Comment by EMREOYUN** [comment]
> If you're running Redis for another project, you can change the socket path in [`include/client.js`](https://github.com/KockaAdmiralac/KockaLogger/blob/master/include/client.js#L78) to have KockaLogger connect to it. Since it's probably not running on a Unix socket, you can change it to something like:
> 
> ```js
>         this._cache = redis.createClient({
>             host: '127.0.0.1',
>             port: 6379
>         })
> ```

This code resolved my issue. Thank you.

**Comment by EMREOYUN** [comment]
Closed #39
