### ISSUE TITLE
Bug report: usernames with ` cause display issues

### ISSUE THREAD

**Issue by kcnotes** [KockaAdmiralac/KockaLogger#45]
## Description
Usernames with multiple backticks are not escaped, causing some issues.

Example user: https://community.fandom.com/wiki/User:Hapie2cu%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60%60

## Expected behavior
Backticks need to be escaped

## Media
![image](https://user-images.githubusercontent.com/5524849/120057848-d7e39180-c089-11eb-872c-a31f2f76b507.png)

**Comment by KockaAdmiralac** [comment]
This *should* no longer happen after https://github.com/KockaAdmiralac/KockaLogger/commit/03ad46f98d466219072fa9a606317919283ea20b, but I can't create an account to test this. Fandom prevents me from creating an account with the name of \`\`\`Really funny\`\`\`, it appears.
